name: live_camera_feed
description: "Live Mobile Camera Feed from the Brilliant Frame"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  frame_msg: ^1.0.0
  simple_frame_app: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/camera.min.lua
    - packages/frame_msg/lua/code.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/plain_text.min.lua
    - assets/frame_app.min.lua
